[env]
TERM = "xterm-256color"

[window]
padding.x = 20
padding.y = 20
dimensions = {columns = 128, lines = 32}

decorations = "Buttonless"
opacity = 0.80
blur = true

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 10.0

[terminal]

[shell]
program = '/bin/zsh'
