# Main format: Character (arrow)
# Directory & Git are on the right
format = """$character """
right_format="""$directory$git_branch  $git_status """

"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true

# Character module - standard arrow [●](white) 
[character]
success_symbol = " [](bold #737c73)"
error_symbol = " [](bold red)"
vimcmd_symbol = " [](bold green)"

[directory.substitutions]
"~" = "󰋜 "

[directory]
read_only = "  "
read_only_style = "red bg:#020202"
format = "[](#020202)[ $path ]($style)[$read_only]($read_only_style)[ ](#020202) "
truncation_length = 10
truncate_to_repo = true
style = "bold italic fg:#737c73 bg:#020202"


[git_branch]
symbol = " "
format = '[$symbol$branch]($style)'
truncation_symbol = '…/'
style = 'bold italic #29B6F6'

[git_status]
format = '[⌠](bold italic #29B6F6)[ $all_status$ahead_behind]($style)[⌡](bold italic #29B6F6)'
style = 'bold italic #29B6F6'
conflicted = '[ ${count}](red) '
up_to_date = '[󰘽](#29B6F6) '
untracked = '[󰋗 ${count}](red) '
ahead = ' ${count} '
diverged = ' ${ahead_count}  ${behind_count} '
behind = ' ${count} '
stashed = '[ ${count}](#29B6F6) '
modified = '[󰛿 ${count}](yellow) '
staged = '[󰐗 ${count}](green) '
renamed = '[󱍸 ${count}](yellow) '
deleted = '[󰍶 ${count}](red) '